# -*- coding: utf-8 -*-
"""sum_product.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eoUJIke6Esifbo44737I2ndKArw92fTh
"""

input=[2,4,6,8,12,14,16,18]
def miss_ele(arr):
    mid=int(len(arr)/2)
    n=len(arr)
    if n==3:
      return arr[0]+arr[2]-arr[1]
    elif n==2:
      return int((arr[0]+arr[1])/2)
    elif abs(arr[mid]-arr[0])/(mid)>abs(arr[n-1]-arr[mid])/(n-mid-1):
      return miss_ele(arr[:mid+1])
    else:
      return miss_ele(arr[mid:])
miss_ele(input)

ini=[-1, -4,-8, -16, -20, -24,-28]
miss_ele(ini)

input=[2,4,6,8,10,12,14,16,20]
def miss_ele(arr):
    mid=int(len(arr)/2)
    n=len(arr)
    if n==3:
      return arr[0]+arr[2]-arr[1]
    elif n==2:
      return int((arr[0]+arr[1])/2)
    elif (arr[mid]-arr[0])/(mid)>(arr[n-1]-arr[mid])/(n-mid-1):
      return miss_ele(arr[:mid+1])
    else: return miss_ele(arr[mid:])
miss_ele(input)

a=[1,1,3]
b=[0,2,3,4,5]
def no_format(a,b):
  while a[0]==0:
    a=a[1:]
  while b[0]==0:
    b=b[1:]
  n=len(a)
  m=len(b)
  c = [0]*(n+m)
  print(c)
  for i in range(n):
    for j in range(m):
      # print("c",n+m-1+i+j)
      # print("a",n-1-i)
      c[n+m-1-i-j]+=a[n-1-i]*b[m-1-j]
      if c[n+m-1-i-j]>9:
        c[n+m-1-i-j] = c[n+m-1-i-j]%10
        c[n+m-2-i-j] = c[n+m-2-i-j]+1
  if c[0]==0:
    c=c[1:]
  return c
no_format(a,b)

113*2345

def no_add(a):
  while a[0]==0:
    a=a[1:]
  n=len(a)-1
  bol=True
  while n!=-1:
    a[n]+=1
    if a[n]>9:
      a[n]=a[n]%10
      n=n-1
    else: n=-1
  if a[0]==0:
    a[0]=1
    a.append(0)
  return a

no_add([0,0,9,9])

